### ISSUE TITLE
server not starting

### ISSUE THREAD

**Issue by ptk2003** [ben-mkiv/MobTools#1]
[main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
[main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER

crash report not creating, attached debug.log
[debug.log](https://github.com/ben-mkiv/MobTools/files/5050517/debug.log)
forge 106, all other mods was temporary removed for test.

**Comment by ben-mkiv** [comment]
Thanks for the report, uploaded a fixed version (1.0.2) to curseForge
https://www.curseforge.com/minecraft/mc-mods/mobtools/files

**Comment by ptk2003** [comment]
thank you, it work fine
